config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    # path('students/', include('students.urls', namesspace='students') )
    path('students/', include('students.urls', namespace='students')),
    path("library/", include("library.urls", namespace="library")),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    # path('show_data/',views.show_data, name='show_data'),
    # path('submit_data/',views.submit_data, name='submit_data'),
    # path('item/<int:item_id>/', views.show_item, name='show_item'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('example/', views.example_view, name='example'),
    path('index/', views.index, name='index'),
    path('student_detail/<int:student_id>/', views.student_detail, name='student_detail'),
    path('student_list/', views.student_list, name='student_list'),
    path('home/', views.home, name='home'),
    path('base/', views.base, name='base'),
    path('header/', views.header, name='header'),
    path('student_create/', views.StudentCreateView.as_view(), name='student_create'),
    path('student_update/<int:pk>/', views.StudentUpdateView.as_view(), name='student_update'),

    path('mymodel/create/', views.MyModelCreteView.as_view(), name='mymodel_create'),
    path('mymodel/list/', views.MyModelListView.as_view(), name='mymodel_list'),
    path('mymodel/detail/<int:pk>/', views.MyModelDetailView.as_view(), name='mymodel_detail'),
    path('mymodel/update/<int:pk>/', views.MyModelUpdateView.as_view(), name='mymodel_update'),
    path('mymodel/delete/<int:pk>/', views.MyModelDeleteView.as_view(), name='mymodel_delete'),

]

users/urls.py
from django.urls import path
from .views import RegisterView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='library:books_list' ), name='logout'),
]

students/models.py
from django.db import models

# Create your models here.
class MyModel(models.Model):
    name = models.CharField(max_length=300)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Group(models.Model):
    name = models.CharField(max_length=100, verbose_name='Группа')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'группа'
        verbose_name_plural = 'группы'
        ordering = ['name']


class Student(models.Model):
    FIRST_YEAR = 'first'
    SECOND_YEAR = 'second'
    THIRD_YEAR = 'third'
    FOURTH_YEAR= 'fourth'

    YEAR_IN_SCHOOL_CHOICES = [
        (FIRST_YEAR, 'Первый курс'),
        (SECOND_YEAR, 'Второй курс'),
        (THIRD_YEAR, 'Третий курс'),
        (FOURTH_YEAR, 'Четвертый курс'),
    ]

    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    email = models.EmailField()
    year = models.CharField(max_length=6, choices=YEAR_IN_SCHOOL_CHOICES, default=FIRST_YEAR, verbose_name='Курс')
    group = models.ForeignKey(Group, related_name='students', on_delete=models.CASCADE),
    enrollment_date = models.DateField(verbose_name='Дата зачисления')
    # default=1

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'студенты'
        ordering = ['last_name']
        permissions = [
            ('can_promote_student', 'Can Promote Student'),
            ('can_expel_student', 'Can expel student'),
        ]

students/forms.py
from django import forms
from .models import Student
from django.core.exceptions import ValidationError


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'year', 'email', 'enrollment_date']

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Введите имя',
        })

        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите фамилию',
        })

        self.fields['year'].widget.attrs.update({
            'class': 'form-control',
        })

        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите email',
        })

        self.fields['enrollment_date'].widget.attrs.update({
            'class': 'form-control',
            'type': 'date'
        })

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email.endswith('@example.com'):
            raise ValidationError('Email должен оканчиваться на @example.com')
        return email

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name and last_name and first_name == last_name:
            self.add_error('last_name', 'Имя и фамилия не могут иметь одинаковые значения')

students/views.py
from django.contrib.messages.api import success
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DeleteView, UpdateView, DetailView, View
from students.models import Student, MyModel
from students.forms import StudentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.http import Http404


class PromoteStudentView(LoginRequiredMixin, View):
    def post(self, request, student_id):
        student = get_object_or_404(Student, id=student_id)

        if not request.user.has_perm('students.can_promote_student'):
            return HttpResponseRedirect("У вас нет прав для перевода студента")

        student.year = next_year(student.year)
        student.save()

        return redirect('students:student_list')

class ExpelStudentView(LoginRequiredMixin, View):
    def post(self, request, student_id):
        student = get_object_or_404(Student, id=student_id)

        if not request.user.has_perm('students.can_expel_student'):
            return HttpResponseRedirect("У вас нет прав для исключения студента студента")

        student.delete()

        return redirect('students:student_list')

class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    template_name = 'students/student_list.html'
    context_object_name = 'students'

    def get_queryset(self):
        if not self.request.user.has_perm('students.view_student'):
            return Student.objects.none()

        return Student.objects.all()

class StudentCreateView(CreateView):
    model = Student
    form_class = StudentForm
    template_name = 'students/student_form.html'
    success_url = reverse_lazy('students:student_list')

class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm
    template_name = 'students/student_form.html'
    success_url = reverse_lazy('students:student_list')



class MyModelCreteView(CreateView):
    model = MyModel
    fields = ['name', 'description']
    template_name = 'students/mymodel_form.html'
    success_url = reverse_lazy('students:mymodel_list')

    def form_valid(self, form):
        form.instance.create_by = self.request.user

        return super().form_valid(form)

    def form_invalid(self, form):
        response = super().form_invalid(form)
        response.context_data['error_message'] = "Please correct the errors"

        return response



class MyModelListView(ListView):
    model = MyModel
    template_name = 'students/mymodel_list.html'
    context_object_name = 'mymodels'

    def get_queryset(self):

        return MyModel.objects.filter(is_active=True)


class MyModelDetailView(DetailView):
    model = MyModel
    TemplateName = 'students/mymodel_detail.html'
    context_object_name = 'mymodel'

    def get_additional_data(self):
        return 'Это дополнительная информация'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['additional_data'] = self.get_additional_data()
        return context

    def get_object(self, queryset =None):
        obj = super().get_object(queryset)
        if not obj.is_active:
            raise Http404("Object not found")
        return obj


class MyModelUpdateView(UpdateView):
    model = MyModel
    fields = ['name', 'description']
    template_name = 'students/mymodel_form.html'
    success_url = reverse_lazy('students:mymodel_list')

class MyModelDeleteView(DeleteView):
    model = MyModel
    template_name = 'students/mymodel_confirm_delete.html'
    success_url = reverse_lazy('students:mymodel_list')



def about(request):
    return render(request, 'students/about.html')

def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        message = request.POST.get('message')

        return HttpResponse(f'Спасибо, {name}! Сообщение получено.')

    return render(request, 'students/contact.html')

def example_view(request):
    return render(request, 'students/example.html')

def index(request):
    student = Student.objects.get(id=1)
    context = {
        'student_name': f'{student.first_name} {student.last_name}',
        'student_year': student.get_year_display(),
    }
    return render(request, 'students/index.html', context=context)

def student_detail(request, student_id):
    student = Student.objects.get(id=student_id)
    context = {
        'student': student,
    }
    return render(request, 'students/student_detail.html', context=context)

def student_list(request):
    students = Student.objects.all()
    context = {
        'students': students,
    }
    return render(request, 'students/student_list.html', context=context)
def home(request):
    student = Student.objects.all()
    context = {
        'student': student,
    }
    return render(request, 'students/home.html', context=context)

def base(request):
    student = Student.objects.all()
    context = {
        'student': student,
    }
    return render(request, 'students/base.html', context=context)

def header(request):
    student = Student.objects.all()
    context = {
        'student': student,
    }
    return render(request, 'students/header.html', context=context)

students/templates/students/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!--
    Мета-тег <meta name="viewport"> — это важный элемент HTML, который определяет,
    как веб-страница будет масштабироваться и отображаться на различных устройствах.
    width=device-width — устанавливает ширину области просмотра равной ширине экрана устройства. телефон, планшет, десктоп
    initial-scale=1.0 — задает начальный масштаб страницы:
    Значение 1.0 означает, что страница будет отображаться в реальном размере (без увеличения или уменьшения)
-->
    <title>О нас</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>О нас</h1>
        <p>
            Добро пожаловать на наш сайт! Мы — команда разработчиков из разных уголков мира, работающая над увлекательными проектами.
        </p>
        <img src="/static/images/icon.png" alt="Logotype" class="img-fluid">
    </div>
<script type="text/javascript" src="/static/js/bootstrap/bootstrap.bundle.min.js"></script>
</body>
</html>

students/templates/students/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Сайт студентов{% endblock %}</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-left: 50px;">
        <a class="navbar-brand" href="#">Сайт студентов</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">О нас</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Контакты</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        {% block content %}{% endblock %}
    </div>
<!-- Подключение Bootstrap JS -->
<script type="text/javascript" src="/static/js/bootstrap/bootstrap.bundle.min.js"></script>
</body>
</html>

students/templates/students/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!--
    Мета-тег <meta name="viewport"> — это важный элемент HTML, который определяет,
    как веб-страница будет масштабироваться и отображаться на различных устройствах.
    width=device-width — устанавливает ширину области просмотра равной ширине экрана устройства. телефон, планшет, десктоп
    initial-scale=1.0 — задает начальный масштаб страницы:
    Значение 1.0 означает, что страница будет отображаться в реальном размере (без увеличения или уменьшения)
-->
    <title>Контактная форма</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1>Свяжитесь с нами</h1>
        <form method="post" action="">
            {% csrf_token %}
            <div class="mb-3">
                <label for="name" class="form-label">Ваше имя</label>
                <input type="text" class="form-control" id="name" name="name" required>
            </div>
            <div class="mb-3">
                <label for="message" class="form-label">Ваше сообщение</label>
                <textarea class="form-control" type="text" id="message" rows="5" name="message" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>
<script type="text/javascript" src="/static/js/bootstrap/bootstrap.bundle.min.js"></script>
</body>
</html>

students/templates/students/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!--
    Мета-тег <meta name="viewport"> — это важный элемент HTML, который определяет,
    как веб-страница будет масштабироваться и отображаться на различных устройствах.
    width=device-width — устанавливает ширину области просмотра равной ширине экрана устройства. телефон, планшет, десктоп
    initial-scale=1.0 — задает начальный масштаб страницы:
    Значение 1.0 означает, что страница будет отображаться в реальном размере (без увеличения или уменьшения)
-->
    <title>Example</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">
</head>
<body>
    <h1>Простой шаблон</h1>
</body>
</html>

students/templates/students/header.html
<header>
    <h1>Сайт студентов</h1>
    <p>Добро пожаловать на сайт студентов!</p>
</header>

students/templates/students/home.html
{% extends 'students/base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <h1>Добро пожаловать на наш сайт!</h1>
    <p>Это главная страница нашего сайта.</p>
{% endblock %}

students/templates/students/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!--
    Мета-тег <meta name="viewport"> — это важный элемент HTML, который определяет,
    как веб-страница будет масштабироваться и отображаться на различных устройствах.
    width=device-width — устанавливает ширину области просмотра равной ширине экрана устройства. телефон, планшет, десктоп
    initial-scale=1.0 — задает начальный масштаб страницы:
    Значение 1.0 означает, что страница будет отображаться в реальном размере (без увеличения или уменьшения)
-->
    <title>Student Info</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">
</head>
<body>
    <h1>Информация о студенте</h1>
    <p> Имя: {{ student_name }}</p>
    <p> Курс: {{ student_year }}</p>
</body>
</html>

students/templates/students/mymodel_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Удаление MyModel</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mb-4">Удалить объект MyModel</h1>
        <p>Вы уверены, что хотите удалить "{{ mymodel.name }}"</p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'students:mymodel_list'%}">Отмена</a>
        </form>
    </div>

    <script type="text/javascript" src="/static/js/bootstrap/bootstrap.bundle.min.js"></script>
</body>
</html>

students/templates/students/mymodel_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Информ MyModel</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mb-4">{{ mymodel.name }}</h1>
        <p>{{ mymodel.description }}</p>
        <p>Создано: {{ mymodel.created_at }}</p>
        <p>Обновлено: {{ mymodel.updated_at }}</p>

    </div>

    <script type="text/javascript" src="/static/js/bootstrap/bootstrap.bundle.min.js"></script>
</body>
</html>

students/templates/students/mymodel_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Форма для MyModel</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mb-4">Форма MyModel</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'students:mymodel_list'%}">Отмена</a>
        </form>
    </div>

    <script type="text/javascript" src="/static/js/bootstrap/bootstrap.bundle.min.js"></script>
</body>
</html>

students/templates/students/mymodel_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список MyModel</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mb-4">Список MyModel</h1>
        <a href="{% url 'students:mymodel_create' %}" class="btn btn-primary">Создать новый MyModel</a>
        <ul class ="list-group">
            {% for mymodel in mymodels  %}
                <li class="list-group-item">
                    <a href="{% url 'students:mymodel_detail' mymodel.pk %}">{{ mymodel.name }}</a>
                    <a href="{% url 'students:mymodel_update' mymodel.pk %}" class="btn btn-secondary">Редактировать</a>
                    <a href="{% url 'students:mymodel_delete' mymodel.pk %}" class="btn btn-danger" >Удалить</a>
                </li>
            {% endfor %}
        </ul>

    </div>
    <script type="text/javascript" src="/static/js/bootstrap/bootstrap.bundle.min.js"></script>
</body>
</html>

students/templates/students/student_detail.html
{% extends 'students/base.html' %}

{% block title %}Детали студента{% endblock %}

{% block content %}
    {% include 'students/header.html' %}
    <h2>Детали студента</h2>
     <p>Имя: {{ student.first_name|upper  }}</p>
    <p>Фамилия: {{ student.last_name }}</p>
    <p>Курс: {{ student.get_year_display|truncatechars:100 }}</p>
{% endblock %}


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
{#    <!--#}
{#    Мета-тег <meta name="viewport"> — это важный элемент HTML, который определяет,#}
{#    как веб-страница будет масштабироваться и отображаться на различных устройствах.#}
{#    width=device-width — устанавливает ширину области просмотра равной ширине экрана устройства. телефон, планшет, десктоп#}
{#    initial-scale=1.0 — задает начальный масштаб страницы:#}
{#    Значение 1.0 означает, что страница будет отображаться в реальном размере (без увеличения или уменьшения)#}
{#-->#}
{#    <title>student_detail</title>#}
{#    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">#}
{##}
{##}
{#</head>#}
{#<body>#}
{##}
{#    <div class="container mt-5">#}
{#        <h1 class="mb-4">Информация о студенте</h1>#}
{#        <p>Имя: {{ student.first_name|upper  }}</p>#}
{#        <p>Фамилия: {{ student.last_name|lower }}</p>#}
{#        <p>Курс: {{ student.get_year_display }}</p>#}
{#        <p>Дата рождения: {{ student.birth_date|date:"d M Y" }}</p>#}
{#        <p>Комментарий: {{ student.comment|default:'Комментарий отсутствует'}}</p>#}
{#        <p>Описание: {{ student.get_year_display|truncatechars:10 }}</p>#}
{#        <p>Фотографии: <img src="{{ student.photo.url }}" alt="{{ student.first_name }} {{ student.last_name }}"></p>#}
{#    </div>#}
{##}
{##}
{##}
{##}
{#    <script type="text/javascript" src="/static/js/bootstrap/bootstrap.bundle.min.js"></script>#}
{#</body>#}
{#</html>#}

students/templates/students/student_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Форма для студента</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">
</head>
<body>
    <div class="container">
        {% if object %}
            <h1 class="mb-4">Форма для редактирования студента</h1>
        {% else %}
            <h1 class="mb-4">Форма для добавления студента</h1>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {% if object %}
                <button type="submit" class="btn btn-primary">Редактировать</button>
                <a href="{% url 'students:student_list'%}">Отмена</a>
            {% else %}
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a href="{% url 'students:student_list'%}">Отмена</a>
            {% endif %}
        </form>
    </div>

    <script type="text/javascript" src="/static/js/bootstrap/bootstrap.bundle.min.js"></script>
</body>
</html>

students/templates/students/student_list.html
{% extends 'students/base.html' %}

{% block title %}Список студентов{% endblock %}

{% block content %}
    {% include 'students/header.html' %}
    <h2>Список студентов</h2>
    <ul class="list-group">
        {% for student in students %}
            <li class="list-group-item">
                    {{ student.first_name }} {{ student.last_name }} - {{ student.year }}
                    {% if perms.students.can_promote_student %}
                        <a href="{% url 'promote_student' %}"> Перевести студента </a>
                    {% endif %}
                    {% if perms.students.can_expel_student %}
                        <a href="{% url 'expel_student' %}"> Исключить студента </a>
                    {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
{#    <title>student_list</title>#}
{#    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css">#}
{#</head>#}
{#<body>#}
{#    <div class="container mt-5">#}
{#        <h1 class="mb-4">Список студентов</h1>#}
{#        <ul class="list-group">#}
{#            {% for student in students %}#}
{#                <li class="list-group-item d-flex justify-content-between align-items-center {%if student.year == 'first'%} list-group-item-primary {%elif student.year == 'second'%} list-group-item-success {%elif student.year == 'third'%} list-group-item-warning {%elif student.year == 'fourth'%} list-group-item-danger {%endif%}">#}
{#                    {{ student.first_name }} {{ student.last_name }}#}
{#                    <span class="badge badge bg-primary text-white rounded-pill">#}
{#                        {% if student.year == 'first' %}#}
{#                            Первый курс#}
{#                        {% elif student.year == 'second' %}#}
{#                            Второй курс#}
{#                        {% elif student.year == 'third' %}#}
{#                            Третий курс#}
{#                        {% elif student.year == 'fourth' %}#}
{#                            Четвертый курс#}
{#                        {% endif %}#}
{#                    </span>#}
{#                </li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    </div>#}
{#    <script type="text/javascript" src="/static/js/bootstrap/bootstrap.bundle.min.js"></script>#}
{#</body>#}
{#</html>#}